### ISSUE TITLE
Lost fail message when fail threshold is met

### ISSUE THREAD

**Issue by cmcmone** [sigcpp/stl-lite#22]
when the verify function throws a message.str() exception, the main method cannot correctly accept this exception and skips to the default exception handling. 

![image](https://user-images.githubusercontent.com/24782194/84699945-69f99500-af20-11ea-90e9-471dbec65b13.png)

**Comment by smurthys** [comment]
Thanks @cmcmone for adding the issue. I changed the issue title to reflect the actual problem, which is that an exception is correctly raised when fail threshold is met, but the driver outputs the extra message `Error -10: Unexpected error`. In this case, the driver should simply stop testing and print summary.

**Comment by smurthys** [comment]
Also, I have analyzed the cause of the problem and traced it to the type of error thrown in function [`verify`](https://github.com/sigcpp/stl-lite/blob/4e56c9059101d4a35ce2741f304ac171999c3b6f/test/tester.cpp#L171).  We need to throw a custom error and catch the custom error in the driver. I have assigned this issue to myself and expect a resolution to be included in Milestone M5.

**Comment by smurthys** [comment]
Just noting here an observation heard from @Ndemco that the details of the failed message is not logged when the fail threshold is met. I revise the issue title to focus on this observation, but that would make the issue more serious.
